[window]
opacity = 0.8
dimensions = { columns = 120, lines = 30 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
bold   = { family = "Fira Code Nerd Font", style = "Bold" }
italic = { family = "Fira Code Nerd Font", style = "Italic" }
size = 11.0

[colors] 
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1A1815" 
foreground = "#E8E0D7" 

[colors.cursor]
text = "#C79F5E"
cursor = "#C79F5E"

[colors.normal]
black   = "0x0C0E14"
red     = "#A8222A"
green   = "0x8EAC67" 
yellow  = "0xCBA62F"
blue    = "#45586A"
magenta = "0xC678DD"
cyan    = "0x89B4C1"
white   = "0xA8AEBF"

[colors.bright]
black   = "0x3B4048"
red     = "0xE06C75"    
green   = "0x98C379"
yellow  = "0xE5C07B"
blue    = "0x61AFEF"
magenta = "0xC678DD"
cyan    = "0x89B4C1"
white   = "0xFFFFFF"

[cursor]
style = { shape = "Block", blinking = "On" }
