[window]
opacity = 0.8
dimensions = { columns = 120, lines = 30 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#073642"
foreground = "#839496"

[colors.cursor]
text = "#002b36"
cursor = "#93a1a1"

[colors.selection]
text = "#002b36"
background = "#93a1a1"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#eee8d5"

[colors.bright]
black   = "#002b36"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#fdf6e3"

[cursor]
style = { shape = "Block", blinking = "On" }
